# Use the official SQLite image as the base image
FROM alpine

# Create a directory to store the database file
RUN mkdir /data

# Copy the SQLite file to the /data directory in the container
COPY data/ /data/

# Set /data as the working directory
WORKDIR /data

