version: "3.9"

networks:
  internal:

volumes:
  data-store:

services:
  store:
    image: ${STORE_IMAGE_NAME}
    container_name: titanic-api-store
    command: sh -c "tail -f /dev/null"
    volumes:
      - data-store:/data
    networks:
      - internal

  api:
    image: ${API_IMAGE_NAME}
    container_name: titanic-api
    depends_on:
      - store
    volumes:
      - data-store:/data-store
    networks:
      - internal
    environment:
      CSV_STORE_PATH: "/data-store/csv/titanic.csv"
      SQLITE_STORE_PATH: "/data-store/sqlite/titanic.db"
      API_PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"


