apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: titanic
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089